on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
    - 'master'
    - 'GH-36'

name: Release 

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Get result
        run: |
          pip install -r release_requirements.txt
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Automated issue for commit: ${{ github.sha }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }'
          echo ${{ secrets.GITHUB_TOKEN }}
          python release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}