on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
    - 'master'
    - 'GH-36'

name: Release 

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get result
        run: |
          pip install -r release_requirements.txt
          python release.py