on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
    - 'master'
    - 'GH-36'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release assets
        run: |
          set -x
          assets=()
          for asset in ./*.md; do
          assets+=("-a" "$asset")
          done
          tag_name="abc"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}